# Generated by Django 5.0.6 on 2026-04-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('biography', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors/')),
            ],
            options={
                'verbose_name': 'Aktyor',
                'verbose_name_plural': 'Aktyorlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Fasl raqami')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='seasons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fasl',
                'verbose_name_plural': 'Fasllar',
                'ordering': ['series', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, default='en', max_length=50)),
                ('age_rating', models.CharField(choices=[('G', 'G — Hammabop'), ('PG', 'PG — Ota-ona nazorati tavsiya etiladi'), ('PG-13', 'PG-13 — 13+'), ('R', 'R — 17+'), ('NC-17', 'NC-17 — 18+')], default='PG-13', max_length=10)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('trailer_url', models.URLField(blank=True)),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium (obuna kerak)')),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiyligi (daqiqa)')),
                ('director', models.CharField(blank=True, max_length=150)),
                ('actors', models.ManyToManyField(blank=True, related_name='%(class)ss', to='content.actor')),
                ('genres', models.ManyToManyField(blank=True, related_name='%(class)ss', to='content.genre')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmlar',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Epizod raqami')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episodes/')),
                ('air_date', models.DateField(blank=True, null=True)),
                ('views_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content.season')),
            ],
            options={
                'verbose_name': 'Epizod',
                'verbose_name_plural': 'Epizodlar',
                'ordering': ['season', 'number'],
                'unique_together': {('season', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, default='en', max_length=50)),
                ('age_rating', models.CharField(choices=[('G', 'G — Hammabop'), ('PG', 'PG — Ota-ona nazorati tavsiya etiladi'), ('PG-13', 'PG-13 — 13+'), ('R', 'R — 17+'), ('NC-17', 'NC-17 — 18+')], default='PG-13', max_length=10)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('trailer_url', models.URLField(blank=True)),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium (obuna kerak)')),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ongoing', 'Davom etmoqda'), ('completed', 'Tugagan'), ('cancelled', 'Bekor qilingan')], default='ongoing', max_length=20)),
                ('total_seasons', models.PositiveIntegerField(default=0)),
                ('total_episodes', models.PositiveIntegerField(default=0)),
                ('actors', models.ManyToManyField(blank=True, related_name='%(class)ss', to='content.actor')),
                ('genres', models.ManyToManyField(blank=True, related_name='%(class)ss', to='content.genre')),
            ],
            options={
                'verbose_name': 'Serial',
                'verbose_name_plural': 'Seriallar',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='content.series'),
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p HD'), ('1080p', '1080p Full HD'), ('1440p', '1440p 2K'), ('2160p', '2160p 4K')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('hls_manifest_url', models.URLField(blank=True, help_text='HLS .m3u8 playlist URL')),
                ('dash_manifest_url', models.URLField(blank=True, help_text='DASH .mpd manifest URL')),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('bitrate_kbps', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Kutmoqda'), ('processing', 'Qayta ishlanmoqda'), ('ready', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='DRM shifrlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='content.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='content.movie')),
            ],
            options={
                'verbose_name': 'Video fayl',
                'verbose_name_plural': 'Video fayllar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='ISO 639-1 kodi, masalan: uz, en, ru', max_length=10)),
                ('language_name', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(help_text='.vtt yoki .srt fayli', upload_to='subtitles/')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='content.videofile')),
            ],
            options={
                'verbose_name': 'Subtitr',
                'verbose_name_plural': 'Subtitrlar',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('language_name', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='content.videofile')),
            ],
            options={
                'verbose_name': 'Audio trek',
                'verbose_name_plural': 'Audio treklar',
                'ordering': ['language'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'number')},
        ),
    ]
