# Generated by Django 5.0.6 on 2026-04-23 08:38

import django.db.models.deletion
import uploads.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('total_size', models.BigIntegerField(help_text='Umumiy fayl hajmi (bayt)')),
                ('uploaded_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('completed', 'Tugallangan'), ('failed', 'Xatolik'), ('cancelled', 'Bekor qilingan')], default='in_progress', max_length=20)),
                ('final_file', models.FileField(blank=True, null=True, upload_to=uploads.models.upload_final_path)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yuklash sessiyasi',
                'verbose_name_plural': 'Yuklash sessiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=uploads.models.upload_chunk_path)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='uploads.upload')),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunklar',
                'ordering': ['chunk_number'],
                'unique_together': {('upload', 'chunk_number')},
            },
        ),
    ]
